#!/bin/bash
cd /etc/httpd/conf.d/users/ && rm -f /etc/httpd/conf.d/users/*
cd /data/foobar && rm -rf ./*
cd /var/log/httpd && rm -f ./*

if ! grep -q /mnt/nfs/data /proc/mounts; then
    mount /mnt/nfs/data && service httpd restart
fi
